x<-c(5,10,15,25,30)
y<-c(-1,NA,75,3,8)
z<-c(5)
x*z
y*z
x
y
z
x*z
a<-c(25,50,75,125,150)
y*z
b<-c(-5,NA,375,15,40)
print(a)
print(b)
y<-ifelse(test=is.na(y)==T,yes=2.5,no=y)
print(y)
load(Data/Assignment_1.csv)
prb<-read.csv(Data/Assignment_1.csv)
mydata<-read.csv("https://raw.githubusercontent.com/mattdemography/EDU_7043/master/Data/Assignment_1.csv")
print(mydata)
head(mydata,n=10)
tbl[1:10,1]
tbl[1:10,1]
tbl<-read.csv("https://raw.githubusercontent.com/mattdemography/EDU_7043/master/Data/Assignment_1.csv")
tbl[1:10,1]
mean(tbl[1:50,3])
median(tbl[1:50,3])
subMN=subset(subMN,State=="CT"|State=="MA"|State=="ME"|State=="NH"|State=="RI"|State=="VT")
newdata<-subset(mydata)
newdata<-subsetMM
subsetMM<-subset(mydata,State=="CT"|State=="MA"|State=="ME"|State=="NH"|State=="RI"|State=="VT")
mean(subsetMM[1:6,3])
mean(subsetMM[1:6,2])
newEnglandVcrime <- subsetMM[1:6,2]
mean(newEnglandVcrime, na.rm = T)
newEnglandVcrime
subsetMM[1:6,3]
subsetMM[1:6,2]
mean(as.numeric(levels(subsetMM[1:6,2])[subsetMM[1:6,2]]))
